#!/usr/bin/env bash
# =============================================================================
# Generates .env for whatever environment this is running in.
#
# Called automatically by .devcontainer/setup.sh when a Codespace is built.
# Safe to run by hand at any time:   bash tools/make_env.sh
#
# The reason this exists as its own script rather than living inside
# .devcontainer/: if the project was uploaded to GitHub through the web
# interface, the dot-folder may not have come along, and this still works.
#
# The one thing that genuinely differs in a Codespace: n8n must know its own
# PUBLIC https address, not localhost. It builds webhook URLs and - critically -
# the approval `$execution.resumeUrl` from WEBHOOK_URL. If that says localhost,
# the Approve/Reject buttons in the approval email point at your own machine and
# do nothing when clicked from a browser tab.
#
# Existing secrets are PRESERVED: rotating N8N_ENCRYPTION_KEY makes previously
# saved n8n credentials unreadable, and rotating POSTGRES_PASSWORD locks n8n out
# of its own database volume.
# =============================================================================
set -euo pipefail

cd "$(dirname "$0")/.."

B=$'\033[1m'; D=$'\033[2m'; G=$'\033[32m'; Y=$'\033[33m'; O=$'\033[0m'
say()  { printf '\n%s==> %s%s\n' "$B" "$1" "$O"; }
ok()   { printf '    %s%s%s\n' "$G" "$1" "$O"; }
warn() { printf '    %s%s%s\n' "$Y" "$1" "$O"; }

# ---------------------------------------------------------------------------
# Work out the public URLs
# ---------------------------------------------------------------------------
say "Detecting environment"

if [[ -n "${CODESPACE_NAME:-}" ]]; then
  DOMAIN="${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}"
  N8N_PUBLIC="https://${CODESPACE_NAME}-5678.${DOMAIN}"
  UI_PUBLIC="https://${CODESPACE_NAME}-8501.${DOMAIN}"
  MAIL_PUBLIC="https://${CODESPACE_NAME}-8025.${DOMAIN}"
  API_PUBLIC="https://${CODESPACE_NAME}-8000.${DOMAIN}"
  SCHEME=https; SECURE_COOKIE=true
  ok "GitHub Codespace: ${CODESPACE_NAME}"
elif [[ -n "${GITPOD_WORKSPACE_URL:-}" ]]; then
  HOSTPART="${GITPOD_WORKSPACE_URL#https://}"
  N8N_PUBLIC="https://5678-${HOSTPART}"
  UI_PUBLIC="https://8501-${HOSTPART}"
  MAIL_PUBLIC="https://8025-${HOSTPART}"
  API_PUBLIC="https://8000-${HOSTPART}"
  SCHEME=https; SECURE_COOKIE=true
  ok "Gitpod workspace"
else
  N8N_PUBLIC="http://localhost:5678"
  UI_PUBLIC="http://localhost:8501"
  MAIL_PUBLIC="http://localhost:8025"
  API_PUBLIC="http://localhost:8000"
  SCHEME=http; SECURE_COOKIE=false
  ok "Local machine - using localhost URLs"
fi

ok "n8n will be served at ${N8N_PUBLIC}"

# ---------------------------------------------------------------------------
# Preserve anything that must not rotate
# ---------------------------------------------------------------------------
read_existing() {  # $1 = key name
  [[ -f .env ]] || return 0
  grep -E "^$1=" .env 2>/dev/null | head -1 | cut -d= -f2- || true
}

ENC_KEY="$(read_existing N8N_ENCRYPTION_KEY)"
if [[ "$ENC_KEY" =~ ^[0-9a-f]{64}$ ]]; then
  ok "reusing the existing N8N_ENCRYPTION_KEY (saved credentials stay valid)"
else
  ENC_KEY="$(openssl rand -hex 32)"
  ok "generated a new N8N_ENCRYPTION_KEY"
fi

PG_PW="$(read_existing POSTGRES_PASSWORD)"
if [[ -n "$PG_PW" && "$PG_PW" != "change_me_local_only" && "$PG_PW" != "replace_me" ]]; then
  ok "reusing the existing POSTGRES_PASSWORD"
else
  PG_PW="$(openssl rand -hex 12)"
  ok "generated a new POSTGRES_PASSWORD"
fi

ITSM_KEY="$(read_existing ITSM_API_KEY)"
[[ -n "$ITSM_KEY" && "$ITSM_KEY" != "local-itsm-key" ]] || ITSM_KEY="$(openssl rand -hex 16)"

# OpenAI key: prefer an already-configured .env value, then the environment
# (a Codespaces secret lands there), then a placeholder.
OPENAI_VALUE="$(read_existing OPENAI_API_KEY)"
if [[ -z "$OPENAI_VALUE" || "$OPENAI_VALUE" == "sk-replace-me" ]]; then
  OPENAI_VALUE="${OPENAI_API_KEY:-sk-replace-me}"
fi

# ---------------------------------------------------------------------------
# Write it
# ---------------------------------------------------------------------------
say "Writing .env"
[[ -f .env ]] && { cp .env ".env.backup.$(date +%s)"; ok "previous .env backed up"; }

cat > .env <<ENVFILE
# =============================================================================
# Generated by tools/make_env.sh - not committed (see .gitignore)
# Regenerate:  bash tools/make_env.sh
# =============================================================================

# --- Postgres ----------------------------------------------------------------
POSTGRES_USER=n8n
POSTGRES_PASSWORD=${PG_PW}
POSTGRES_DB=n8n
POSTGRES_PORT=5432

# --- n8n ---------------------------------------------------------------------
N8N_ENCRYPTION_KEY=${ENC_KEY}
N8N_PORT=5678
N8N_LOG_LEVEL=info
GENERIC_TIMEZONE=Asia/Kolkata

# These four are what make webhooks and approval links work from a browser.
N8N_HOST=${N8N_PUBLIC#*://}
N8N_PROTOCOL=${SCHEME}
N8N_SECURE_COOKIE=${SECURE_COOKIE}
WEBHOOK_URL=${N8N_PUBLIC}/

# --- OpenAI (requirement 4.4) ------------------------------------------------
OPENAI_API_KEY=${OPENAI_VALUE}
OPENAI_MODEL=gpt-4o-mini

# --- Mock external Enterprise IT system (requirement 4.6) --------------------
ITSM_API_KEY=${ITSM_KEY}

# --- Business rules ----------------------------------------------------------
APPROVAL_COST_THRESHOLD=25000
MIN_LLM_CONFIDENCE=0.55
APPROVAL_TIMEOUT_HOURS=48

# --- Notification addressing -------------------------------------------------
SERVICE_DESK_FROM=servicedesk@tcs-demo.local
IT_OPS_EMAIL=it-ops@tcs-demo.local
ESCALATION_EMAIL=it-head@tcs-demo.local

# The console links to Mailpit, so this is the address your BROWSER reaches,
# not the container hostname.
MAILPIT_URL=${MAIL_PUBLIC}

# --- Evaluation harness ------------------------------------------------------
# Inside the container, localhost is faster and skips port-forwarding auth.
EVAL_WEBHOOK_URL=http://localhost:5678/webhook/it-request
EVAL_CONCURRENCY=4
ITSM_API_BASE=http://localhost:8000
DATABASE_URL=postgresql://n8n:${PG_PW}@localhost:5432/n8n
ENVFILE

ok ".env written"

if [[ "$OPENAI_VALUE" == "sk-replace-me" ]]; then
  warn "OPENAI_API_KEY is still a placeholder"
  warn "  set it in .env, or as a repo Codespaces secret named OPENAI_API_KEY"
  warn "  (without it the pipeline still runs - it falls back to keyword"
  warn "   classification and routes to Human Review, worth demonstrating)"
else
  ok "OPENAI_API_KEY is set"
fi

# ---------------------------------------------------------------------------
# Record the URLs for tools/show_urls.sh
# ---------------------------------------------------------------------------
mkdir -p .runtime
cat > .runtime/urls <<URLS
N8N_URL=${N8N_PUBLIC}
UI_URL=${UI_PUBLIC}
MAIL_URL=${MAIL_PUBLIC}
API_URL=${API_PUBLIC}
PG_PW=${PG_PW}
URLS

printf '\n%sDone.%s Next:  %sdocker compose up -d%s   then   %sbash tools/show_urls.sh%s\n\n' \
  "$B" "$O" "$G" "$O" "$G" "$O"
